openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:5432
tags:
  - name: Tasks
    description: Task-related endpoints
paths:
  /tasks/{id}:
    $ref: paths/tasks_{id}.yaml
